// Package queryopenapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package queryopenapi

import (
	"encoding/json"
	"errors"
	"time"
	"github.com/shpandrak/shpanstream/utils/timeseries"
	"github.com/shpandrak/shpanstream/utils/timeseries/tsquery"
)

// Defines values for ApiAlignerFilterType.
const (
	ApiAlignerFilterTypeAligner ApiAlignerFilterType = "aligner"
)

// Defines values for ApiAppendFieldReportFilterType.
const (
	ApiAppendFieldReportFilterTypeAppendField ApiAppendFieldReportFilterType = "appendField"
)

// Defines values for ApiCalendarAlignmentPeriodType.
const (
	ApiCalendarAlignmentPeriodTypeCalendar ApiCalendarAlignmentPeriodType = "calendar"
)

// Defines values for ApiCalendarPeriodType.
const (
	ApiCalendarPeriodTypeDay         ApiCalendarPeriodType = "day"
	ApiCalendarPeriodTypeHalfYear    ApiCalendarPeriodType = "halfYear"
	ApiCalendarPeriodTypeHour        ApiCalendarPeriodType = "hour"
	ApiCalendarPeriodTypeMonth       ApiCalendarPeriodType = "month"
	ApiCalendarPeriodTypeQuarter     ApiCalendarPeriodType = "quarter"
	ApiCalendarPeriodTypeQuarterHour ApiCalendarPeriodType = "quarterHour"
	ApiCalendarPeriodTypeWeek        ApiCalendarPeriodType = "week"
	ApiCalendarPeriodTypeYear        ApiCalendarPeriodType = "year"
)

// Defines values for ApiCastQueryFieldValueType.
const (
	ApiCastQueryFieldValueTypeCast ApiCastQueryFieldValueType = "cast"
)

// Defines values for ApiCastReportFieldValueType.
const (
	ApiCastReportFieldValueTypeCast ApiCastReportFieldValueType = "cast"
)

// Defines values for ApiConditionFilterType.
const (
	ApiConditionFilterTypeCondition ApiConditionFilterType = "condition"
)

// Defines values for ApiConditionQueryFieldValueType.
const (
	ApiConditionQueryFieldValueTypeCondition ApiConditionQueryFieldValueType = "condition"
)

// Defines values for ApiConditionReportFieldValueType.
const (
	ApiConditionReportFieldValueTypeCondition ApiConditionReportFieldValueType = "condition"
)

// Defines values for ApiConditionReportFilterType.
const (
	ApiConditionReportFilterTypeCondition ApiConditionReportFilterType = "condition"
)

// Defines values for ApiConstantQueryFieldValueType.
const (
	ApiConstantQueryFieldValueTypeConstant ApiConstantQueryFieldValueType = "constant"
)

// Defines values for ApiConstantReportFieldValueType.
const (
	ApiConstantReportFieldValueTypeConstant ApiConstantReportFieldValueType = "constant"
)

// Defines values for ApiCustomAlignmentPeriodType.
const (
	ApiCustomAlignmentPeriodTypeCustom ApiCustomAlignmentPeriodType = "custom"
)

// Defines values for ApiDeltaFilterType.
const (
	ApiDeltaFilterTypeDelta ApiDeltaFilterType = "delta"
)

// Defines values for ApiDropFieldsReportFilterType.
const (
	ApiDropFieldsReportFilterTypeDropFields ApiDropFieldsReportFilterType = "dropFields"
)

// Defines values for ApiFieldValueFilterType.
const (
	ApiFieldValueFilterTypeFieldValue ApiFieldValueFilterType = "fieldValue"
)

// Defines values for ApiFilteredMultiDatasourceType.
const (
	ApiFilteredMultiDatasourceTypeFiltered ApiFilteredMultiDatasourceType = "filtered"
)

// Defines values for ApiFilteredQueryDatasourceType.
const (
	ApiFilteredQueryDatasourceTypeFiltered ApiFilteredQueryDatasourceType = "filtered"
)

// Defines values for ApiFilteredReportDatasourceType.
const (
	ApiFilteredReportDatasourceTypeFiltered ApiFilteredReportDatasourceType = "filtered"
)

// Defines values for ApiFilteredReportMultiDatasourceType.
const (
	ApiFilteredReportMultiDatasourceTypeFiltered ApiFilteredReportMultiDatasourceType = "filtered"
)

// Defines values for ApiFromDatasourceReportDatasourceType.
const (
	ApiFromDatasourceReportDatasourceTypeFromDatasource ApiFromDatasourceReportDatasourceType = "fromDatasource"
)

// Defines values for ApiFromMultiDatasourceReportMultiDatasourceType.
const (
	ApiFromMultiDatasourceReportMultiDatasourceTypeFromMultiDatasource ApiFromMultiDatasourceReportMultiDatasourceType = "fromMultiDatasource"
)

// Defines values for ApiFromReportQueryDatasourceType.
const (
	ApiFromReportQueryDatasourceTypeFromReport ApiFromReportQueryDatasourceType = "fromReport"
)

// Defines values for ApiJoinReportDatasourceType.
const (
	ApiJoinReportDatasourceTypeJoin ApiJoinReportDatasourceType = "join"
)

// Defines values for ApiJoinType.
const (
	ApiJoinTypeFull  ApiJoinType = "full"
	ApiJoinTypeInner ApiJoinType = "inner"
	ApiJoinTypeLeft  ApiJoinType = "left"
)

// Defines values for ApiListMultiDatasourceType.
const (
	ApiListMultiDatasourceTypeList ApiListMultiDatasourceType = "list"
)

// Defines values for ApiListReportMultiDatasourceType.
const (
	ApiListReportMultiDatasourceTypeList ApiListReportMultiDatasourceType = "list"
)

// Defines values for ApiLogicalExpressionQueryFieldValueType.
const (
	ApiLogicalExpressionQueryFieldValueTypeLogicalExpression ApiLogicalExpressionQueryFieldValueType = "logicalExpression"
)

// Defines values for ApiLogicalExpressionReportFieldValueType.
const (
	ApiLogicalExpressionReportFieldValueTypeLogicalExpression ApiLogicalExpressionReportFieldValueType = "logicalExpression"
)

// Defines values for ApiNilQueryFieldValueType.
const (
	ApiNilQueryFieldValueTypeNil ApiNilQueryFieldValueType = "nil"
)

// Defines values for ApiNilReportFieldValueType.
const (
	ApiNilReportFieldValueTypeNil ApiNilReportFieldValueType = "nil"
)

// Defines values for ApiNumericExpressionQueryFieldValueType.
const (
	ApiNumericExpressionQueryFieldValueTypeNumericExpression ApiNumericExpressionQueryFieldValueType = "numericExpression"
)

// Defines values for ApiNumericExpressionReportFieldValueType.
const (
	ApiNumericExpressionReportFieldValueTypeNumericExpression ApiNumericExpressionReportFieldValueType = "numericExpression"
)

// Defines values for ApiNvlQueryFieldValueType.
const (
	ApiNvlQueryFieldValueTypeNvl ApiNvlQueryFieldValueType = "nvl"
)

// Defines values for ApiNvlReportFieldValueType.
const (
	ApiNvlReportFieldValueTypeNvl ApiNvlReportFieldValueType = "nvl"
)

// Defines values for ApiOverrideFieldMetadataFilterType.
const (
	ApiOverrideFieldMetadataFilterTypeOverrideFieldMetadata ApiOverrideFieldMetadataFilterType = "overrideFieldMetadata"
)

// Defines values for ApiProjectionReportFilterType.
const (
	ApiProjectionReportFilterTypeProjection ApiProjectionReportFilterType = "projection"
)

// Defines values for ApiRateFilterType.
const (
	ApiRateFilterTypeRate ApiRateFilterType = "rate"
)

// Defines values for ApiReduceReportFieldValueType.
const (
	ApiReduceReportFieldValueTypeReduce ApiReduceReportFieldValueType = "reduce"
)

// Defines values for ApiReductionQueryDatasourceType.
const (
	ApiReductionQueryDatasourceTypeReduction ApiReductionQueryDatasourceType = "reduction"
)

// Defines values for ApiRefQueryFieldValueType.
const (
	ApiRefQueryFieldValueTypeRef ApiRefQueryFieldValueType = "ref"
)

// Defines values for ApiRefReportFieldValueType.
const (
	ApiRefReportFieldValueTypeRef ApiRefReportFieldValueType = "ref"
)

// Defines values for ApiSelectorQueryFieldValueType.
const (
	ApiSelectorQueryFieldValueTypeSelector ApiSelectorQueryFieldValueType = "selector"
)

// Defines values for ApiSelectorReportFieldValueType.
const (
	ApiSelectorReportFieldValueTypeSelector ApiSelectorReportFieldValueType = "selector"
)

// Defines values for ApiSingleFieldReportFilterType.
const (
	ApiSingleFieldReportFilterTypeSingleField ApiSingleFieldReportFilterType = "singleField"
)

// Defines values for ApiStaticQueryDatasourceType.
const (
	ApiStaticQueryDatasourceTypeStatic ApiStaticQueryDatasourceType = "static"
)

// Defines values for ApiStaticReportDatasourceType.
const (
	ApiStaticReportDatasourceTypeStatic ApiStaticReportDatasourceType = "static"
)

// Defines values for ApiUnaryNumericOperatorQueryFieldValueType.
const (
	ApiUnaryNumericOperatorQueryFieldValueTypeUnaryNumericOperator ApiUnaryNumericOperatorQueryFieldValueType = "unaryNumericOperator"
)

// Defines values for ApiUnaryNumericOperatorReportFieldValueType.
const (
	ApiUnaryNumericOperatorReportFieldValueTypeUnaryNumericOperator ApiUnaryNumericOperatorReportFieldValueType = "unaryNumericOperator"
)

// ApiAddFieldMeta defines model for ApiAddFieldMeta.
type ApiAddFieldMeta struct {
	CustomMetadata map[string]interface{} `json:"customMetadata,omitempty"`
	OverrideUnit   string                 `json:"overrideUnit,omitempty"`
	Uri            string                 `json:"uri"`
}

// ApiAlignerFilter defines model for ApiAlignerFilter.
type ApiAlignerFilter struct {
	AlignerPeriod ApiAlignmentPeriod   `json:"alignerPeriod"`
	FillMode      *ApiFillMode         `json:"fillMode,omitempty"`
	Type          ApiAlignerFilterType `json:"type"`
}

// ApiAlignerFilterType defines model for ApiAlignerFilter.Type.
type ApiAlignerFilterType string

// ApiAlignmentPeriod defines model for ApiAlignmentPeriod.
type ApiAlignmentPeriod struct {
	union json.RawMessage
}

// ApiAppendFieldReportFilter Appends a new computed field to the report. Maps to report.AppendFieldFilter.
type ApiAppendFieldReportFilter struct {
	FieldMeta  ApiAddFieldMeta                `json:"fieldMeta"`
	FieldValue ApiReportFieldValue            `json:"fieldValue"`
	Type       ApiAppendFieldReportFilterType `json:"type"`
}

// ApiAppendFieldReportFilterType defines model for ApiAppendFieldReportFilter.Type.
type ApiAppendFieldReportFilterType string

// ApiBinaryNumericOperatorType defines model for ApiBinaryNumericOperatorType.
type ApiBinaryNumericOperatorType = tsquery.BinaryNumericOperatorType

// ApiCalendarAlignmentPeriod defines model for ApiCalendarAlignmentPeriod.
type ApiCalendarAlignmentPeriod struct {
	AlignmentPeriodType ApiCalendarPeriodType          `json:"alignmentPeriodType"`
	Type                ApiCalendarAlignmentPeriodType `json:"type"`
	ZoneId              string                         `json:"zoneId"`
}

// ApiCalendarAlignmentPeriodType defines model for ApiCalendarAlignmentPeriod.Type.
type ApiCalendarAlignmentPeriodType string

// ApiCalendarPeriodType defines model for ApiCalendarPeriodType.
type ApiCalendarPeriodType string

// ApiCastQueryFieldValue defines model for ApiCastQueryFieldValue.
type ApiCastQueryFieldValue struct {
	Source     ApiQueryFieldValue         `json:"source"`
	TargetType ApiMetricDataType          `json:"targetType"`
	Type       ApiCastQueryFieldValueType `json:"type"`
}

// ApiCastQueryFieldValueType defines model for ApiCastQueryFieldValue.Type.
type ApiCastQueryFieldValueType string

// ApiCastReportFieldValue defines model for ApiCastReportFieldValue.
type ApiCastReportFieldValue struct {
	Source     ApiReportFieldValue         `json:"source"`
	TargetType ApiMetricDataType           `json:"targetType"`
	Type       ApiCastReportFieldValueType `json:"type"`
}

// ApiCastReportFieldValueType defines model for ApiCastReportFieldValue.Type.
type ApiCastReportFieldValueType string

// ApiConditionFilter defines model for ApiConditionFilter.
type ApiConditionFilter struct {
	BooleanField ApiQueryFieldValue     `json:"booleanField"`
	Type         ApiConditionFilterType `json:"type"`
}

// ApiConditionFilterType defines model for ApiConditionFilter.Type.
type ApiConditionFilterType string

// ApiConditionOperatorType defines model for ApiConditionOperatorType.
type ApiConditionOperatorType = tsquery.ConditionOperatorType

// ApiConditionQueryFieldValue defines model for ApiConditionQueryFieldValue.
type ApiConditionQueryFieldValue struct {
	Operand1     ApiQueryFieldValue              `json:"operand1"`
	Operand2     ApiQueryFieldValue              `json:"operand2"`
	OperatorType ApiConditionOperatorType        `json:"operatorType"`
	Type         ApiConditionQueryFieldValueType `json:"type"`
}

// ApiConditionQueryFieldValueType defines model for ApiConditionQueryFieldValue.Type.
type ApiConditionQueryFieldValueType string

// ApiConditionReportFieldValue defines model for ApiConditionReportFieldValue.
type ApiConditionReportFieldValue struct {
	Operand1     ApiReportFieldValue              `json:"operand1"`
	Operand2     ApiReportFieldValue              `json:"operand2"`
	OperatorType ApiConditionOperatorType         `json:"operatorType"`
	Type         ApiConditionReportFieldValueType `json:"type"`
}

// ApiConditionReportFieldValueType defines model for ApiConditionReportFieldValue.Type.
type ApiConditionReportFieldValueType string

// ApiConditionReportFilter Filters report rows based on a boolean expression. Only rows where the condition evaluates to true are kept.
type ApiConditionReportFilter struct {
	BooleanField ApiReportFieldValue          `json:"booleanField"`
	Type         ApiConditionReportFilterType `json:"type"`
}

// ApiConditionReportFilterType defines model for ApiConditionReportFilter.Type.
type ApiConditionReportFilterType string

// ApiConstantQueryFieldValue defines model for ApiConstantQueryFieldValue.
type ApiConstantQueryFieldValue struct {
	DataType   ApiMetricDataType              `json:"dataType"`
	FieldValue any                            `json:"fieldValue"`
	Required   bool                           `json:"required"`
	Type       ApiConstantQueryFieldValueType `json:"type"`
	Unit       string                         `json:"unit,omitempty"`
}

// ApiConstantQueryFieldValueType defines model for ApiConstantQueryFieldValue.Type.
type ApiConstantQueryFieldValueType string

// ApiConstantReportFieldValue defines model for ApiConstantReportFieldValue.
type ApiConstantReportFieldValue struct {
	DataType   ApiMetricDataType               `json:"dataType"`
	FieldValue any                             `json:"fieldValue"`
	Required   bool                            `json:"required"`
	Type       ApiConstantReportFieldValueType `json:"type"`
	Unit       string                          `json:"unit,omitempty"`
}

// ApiConstantReportFieldValueType defines model for ApiConstantReportFieldValue.Type.
type ApiConstantReportFieldValueType string

// ApiCustomAlignmentPeriod defines model for ApiCustomAlignmentPeriod.
type ApiCustomAlignmentPeriod struct {
	DurationInMillis int64                        `json:"durationInMillis"`
	Type             ApiCustomAlignmentPeriodType `json:"type"`
	ZoneId           string                       `json:"zoneId"`
}

// ApiCustomAlignmentPeriodType defines model for ApiCustomAlignmentPeriod.Type.
type ApiCustomAlignmentPeriodType string

// ApiDeltaFilter Delta filter computes the difference between consecutive values (current - previous). Requires numeric, required field.
// When nonNegative is true, the filter handles counter resets: if the current value is negative, the point is dropped;
// if the current value is less than the previous (reset detected), the delta is the current value (assuming reset from zero),
// or if maxCounterValue is set, the delta is (maxCounterValue - previous + current) to handle counter wraparound.
type ApiDeltaFilter struct {
	// MaxCounterValue Maximum counter value for wraparound detection. Only used when nonNegative is true. When set, counter resets compute delta as (maxCounterValue - previous + current).
	MaxCounterValue float64 `json:"maxCounterValue,omitempty"`

	// NonNegative When true, handles counter resets by clamping negative deltas. Decreases are treated as counter resets.
	NonNegative bool               `json:"nonNegative,omitempty"`
	Type        ApiDeltaFilterType `json:"type"`
}

// ApiDeltaFilterType defines model for ApiDeltaFilter.Type.
type ApiDeltaFilterType string

// ApiDropFieldsReportFilter Drops specified fields from the report by URN. Maps to report.DropFieldsFilter.
type ApiDropFieldsReportFilter struct {
	FieldUrns []string                      `json:"fieldUrns"`
	Type      ApiDropFieldsReportFilterType `json:"type"`
}

// ApiDropFieldsReportFilterType defines model for ApiDropFieldsReportFilter.Type.
type ApiDropFieldsReportFilterType string

// ApiExecuteQueryCommandArgs defines model for ApiExecuteQueryCommandArgs.
type ApiExecuteQueryCommandArgs struct {
	// Datasource Datasource for query. datasource can either be a source of data (e.g. from a database or api) or a manipulation of data (e.g. filtered, reduction, etc.)
	Datasource ApiQueryDatasource `json:"datasource"`
	From       time.Time          `json:"from"`
	To         time.Time          `json:"to"`
}

// ApiFieldValueFilter defines model for ApiFieldValueFilter.
type ApiFieldValueFilter struct {
	FieldMeta  ApiAddFieldMeta         `json:"fieldMeta"`
	FieldValue ApiQueryFieldValue      `json:"fieldValue"`
	Type       ApiFieldValueFilterType `json:"type"`
}

// ApiFieldValueFilterType defines model for ApiFieldValueFilter.Type.
type ApiFieldValueFilterType string

// ApiFillMode defines model for ApiFillMode.
type ApiFillMode = timeseries.FillMode

// ApiFilteredMultiDatasource Wraps another multi-datasource and applies filters to each datasource it yields.
type ApiFilteredMultiDatasource struct {
	Filters []ApiQueryFilter `json:"filters"`

	// MultiDatasource Multi Datasource is a collection of datasources, either static or a result of a dynamic query.
	MultiDatasource ApiMultiDatasource             `json:"multiDatasource"`
	Type            ApiFilteredMultiDatasourceType `json:"type"`
}

// ApiFilteredMultiDatasourceType defines model for ApiFilteredMultiDatasource.Type.
type ApiFilteredMultiDatasourceType string

// ApiFilteredQueryDatasource defines model for ApiFilteredQueryDatasource.
type ApiFilteredQueryDatasource struct {
	// Datasource Datasource for query. datasource can either be a source of data (e.g. from a database or api) or a manipulation of data (e.g. filtered, reduction, etc.)
	Datasource ApiQueryDatasource             `json:"datasource"`
	Filters    []ApiQueryFilter               `json:"filters"`
	Type       ApiFilteredQueryDatasourceType `json:"type"`
}

// ApiFilteredQueryDatasourceType defines model for ApiFilteredQueryDatasource.Type.
type ApiFilteredQueryDatasourceType string

// ApiFilteredReportDatasource Applies filters to a report datasource.
type ApiFilteredReportDatasource struct {
	Filters []ApiReportFilter `json:"filters"`

	// ReportDatasource Report datasource that produces multiple fields per timestamp.
	ReportDatasource ApiReportDatasource             `json:"reportDatasource"`
	Type             ApiFilteredReportDatasourceType `json:"type"`
}

// ApiFilteredReportDatasourceType defines model for ApiFilteredReportDatasource.Type.
type ApiFilteredReportDatasourceType string

// ApiFilteredReportMultiDatasource Wraps another report multi-datasource and applies report filters to each datasource it yields.
type ApiFilteredReportMultiDatasource struct {
	Filters []ApiReportFilter `json:"filters"`

	// ReportMultiDatasource Multi datasource for reports - a collection of report datasources.
	ReportMultiDatasource ApiReportMultiDatasource             `json:"reportMultiDatasource"`
	Type                  ApiFilteredReportMultiDatasourceType `json:"type"`
}

// ApiFilteredReportMultiDatasourceType defines model for ApiFilteredReportMultiDatasource.Type.
type ApiFilteredReportMultiDatasourceType string

// ApiFromDatasourceReportDatasource Wraps a standard query datasource as a report datasource (single field).
type ApiFromDatasourceReportDatasource struct {
	// Datasource Datasource for query. datasource can either be a source of data (e.g. from a database or api) or a manipulation of data (e.g. filtered, reduction, etc.)
	Datasource ApiQueryDatasource                    `json:"datasource"`
	Type       ApiFromDatasourceReportDatasourceType `json:"type"`
}

// ApiFromDatasourceReportDatasourceType defines model for ApiFromDatasourceReportDatasource.Type.
type ApiFromDatasourceReportDatasourceType string

// ApiFromMultiDatasourceReportMultiDatasource Wraps a standard multi datasource as a report multi datasource.
type ApiFromMultiDatasourceReportMultiDatasource struct {
	// MultiDatasource Multi Datasource is a collection of datasources, either static or a result of a dynamic query.
	MultiDatasource ApiMultiDatasource                              `json:"multiDatasource"`
	Type            ApiFromMultiDatasourceReportMultiDatasourceType `json:"type"`
}

// ApiFromMultiDatasourceReportMultiDatasourceType defines model for ApiFromMultiDatasourceReportMultiDatasource.Type.
type ApiFromMultiDatasourceReportMultiDatasourceType string

// ApiFromReportQueryDatasource Extracts a single field from a report datasource as a standard query datasource.
type ApiFromReportQueryDatasource struct {
	// FieldUrn URN of the field to extract from the report.
	FieldUrn string `json:"fieldUrn"`

	// ReportDatasource Report datasource that produces multiple fields per timestamp.
	ReportDatasource ApiReportDatasource              `json:"reportDatasource"`
	Type             ApiFromReportQueryDatasourceType `json:"type"`
}

// ApiFromReportQueryDatasourceType defines model for ApiFromReportQueryDatasource.Type.
type ApiFromReportQueryDatasourceType string

// ApiJoinReportDatasource Joins multiple report datasources based on timestamp.
type ApiJoinReportDatasource struct {
	// JoinType Type of join operation.
	JoinType ApiJoinType `json:"joinType"`

	// MultiDatasource Multi datasource for reports - a collection of report datasources.
	MultiDatasource ApiReportMultiDatasource    `json:"multiDatasource"`
	Type            ApiJoinReportDatasourceType `json:"type"`
}

// ApiJoinReportDatasourceType defines model for ApiJoinReportDatasource.Type.
type ApiJoinReportDatasourceType string

// ApiJoinType Type of join operation.
type ApiJoinType string

// ApiListMultiDatasource List Multi Datasource is a static predefined list of datasources.
type ApiListMultiDatasource struct {
	Datasources []ApiQueryDatasource       `json:"datasources"`
	Type        ApiListMultiDatasourceType `json:"type"`
}

// ApiListMultiDatasourceType defines model for ApiListMultiDatasource.Type.
type ApiListMultiDatasourceType string

// ApiListReportMultiDatasource List of report datasources.
type ApiListReportMultiDatasource struct {
	Datasources []ApiReportDatasource            `json:"datasources"`
	Type        ApiListReportMultiDatasourceType `json:"type"`
}

// ApiListReportMultiDatasourceType defines model for ApiListReportMultiDatasource.Type.
type ApiListReportMultiDatasourceType string

// ApiLogicalExpressionQueryFieldValue defines model for ApiLogicalExpressionQueryFieldValue.
type ApiLogicalExpressionQueryFieldValue struct {
	LogicalOperatorType ApiLogicalOperatorType                  `json:"logicalOperatorType"`
	Operand1            ApiQueryFieldValue                      `json:"operand1"`
	Operand2            ApiQueryFieldValue                      `json:"operand2"`
	Type                ApiLogicalExpressionQueryFieldValueType `json:"type"`
}

// ApiLogicalExpressionQueryFieldValueType defines model for ApiLogicalExpressionQueryFieldValue.Type.
type ApiLogicalExpressionQueryFieldValueType string

// ApiLogicalExpressionReportFieldValue defines model for ApiLogicalExpressionReportFieldValue.
type ApiLogicalExpressionReportFieldValue struct {
	LogicalOperatorType ApiLogicalOperatorType                   `json:"logicalOperatorType"`
	Operand1            ApiReportFieldValue                      `json:"operand1"`
	Operand2            ApiReportFieldValue                      `json:"operand2"`
	Type                ApiLogicalExpressionReportFieldValueType `json:"type"`
}

// ApiLogicalExpressionReportFieldValueType defines model for ApiLogicalExpressionReportFieldValue.Type.
type ApiLogicalExpressionReportFieldValueType string

// ApiLogicalOperatorType defines model for ApiLogicalOperatorType.
type ApiLogicalOperatorType = tsquery.LogicalOperatorType

// ApiMeasurementValue defines model for ApiMeasurementValue.
type ApiMeasurementValue struct {
	Timestamp time.Time `json:"timestamp"`
	Value     any       `json:"value"`
}

// ApiMetricDataType defines model for ApiMetricDataType.
type ApiMetricDataType = tsquery.DataType

// ApiMultiDatasource Multi Datasource is a collection of datasources, either static or a result of a dynamic query.
type ApiMultiDatasource struct {
	union json.RawMessage
}

// ApiNilQueryFieldValue Represents a nil/null value with a specified data type. Always has required=false.
type ApiNilQueryFieldValue struct {
	DataType ApiMetricDataType         `json:"dataType"`
	Type     ApiNilQueryFieldValueType `json:"type"`
	Unit     string                    `json:"unit,omitempty"`
}

// ApiNilQueryFieldValueType defines model for ApiNilQueryFieldValue.Type.
type ApiNilQueryFieldValueType string

// ApiNilReportFieldValue Represents a nil/null value with a specified data type. Always has required=false.
type ApiNilReportFieldValue struct {
	DataType ApiMetricDataType          `json:"dataType"`
	Type     ApiNilReportFieldValueType `json:"type"`
	Unit     string                     `json:"unit,omitempty"`
}

// ApiNilReportFieldValueType defines model for ApiNilReportFieldValue.Type.
type ApiNilReportFieldValueType string

// ApiNumericExpressionQueryFieldValue defines model for ApiNumericExpressionQueryFieldValue.
type ApiNumericExpressionQueryFieldValue struct {
	Op   ApiBinaryNumericOperatorType            `json:"op"`
	Op1  ApiQueryFieldValue                      `json:"op1"`
	Op2  ApiQueryFieldValue                      `json:"op2"`
	Type ApiNumericExpressionQueryFieldValueType `json:"type"`
}

// ApiNumericExpressionQueryFieldValueType defines model for ApiNumericExpressionQueryFieldValue.Type.
type ApiNumericExpressionQueryFieldValueType string

// ApiNumericExpressionReportFieldValue defines model for ApiNumericExpressionReportFieldValue.
type ApiNumericExpressionReportFieldValue struct {
	Op   ApiBinaryNumericOperatorType             `json:"op"`
	Op1  ApiReportFieldValue                      `json:"op1"`
	Op2  ApiReportFieldValue                      `json:"op2"`
	Type ApiNumericExpressionReportFieldValueType `json:"type"`
}

// ApiNumericExpressionReportFieldValueType defines model for ApiNumericExpressionReportFieldValue.Type.
type ApiNumericExpressionReportFieldValueType string

// ApiNvlQueryFieldValue defines model for ApiNvlQueryFieldValue.
type ApiNvlQueryFieldValue struct {
	AltField ApiQueryFieldValue        `json:"altField"`
	Source   ApiQueryFieldValue        `json:"source"`
	Type     ApiNvlQueryFieldValueType `json:"type"`
}

// ApiNvlQueryFieldValueType defines model for ApiNvlQueryFieldValue.Type.
type ApiNvlQueryFieldValueType string

// ApiNvlReportFieldValue defines model for ApiNvlReportFieldValue.
type ApiNvlReportFieldValue struct {
	AltField ApiReportFieldValue        `json:"altField"`
	Source   ApiReportFieldValue        `json:"source"`
	Type     ApiNvlReportFieldValueType `json:"type"`
}

// ApiNvlReportFieldValueType defines model for ApiNvlReportFieldValue.Type.
type ApiNvlReportFieldValueType string

// ApiOverrideFieldMetadataFilter defines model for ApiOverrideFieldMetadataFilter.
type ApiOverrideFieldMetadataFilter struct {
	Type              ApiOverrideFieldMetadataFilterType `json:"type"`
	UpdatedCustomMeta map[string]interface{}             `json:"updatedCustomMeta,omitempty"`
	UpdatedUnit       string                             `json:"updatedUnit,omitempty"`
	UpdatedUrn        string                             `json:"updatedUrn,omitempty"`
}

// ApiOverrideFieldMetadataFilterType defines model for ApiOverrideFieldMetadataFilter.Type.
type ApiOverrideFieldMetadataFilterType string

// ApiProjectionReportFilter Projects/selects specific fields from the report by URN, dropping all others. Only supports referencing existing fields (no computed values).
type ApiProjectionReportFilter struct {
	// FieldUrns URNs of fields to keep. All other fields are dropped.
	FieldUrns []string                      `json:"fieldUrns"`
	Type      ApiProjectionReportFilterType `json:"type"`
}

// ApiProjectionReportFilterType defines model for ApiProjectionReportFilter.Type.
type ApiProjectionReportFilterType string

// ApiQueryDatasource Datasource for query. datasource can either be a source of data (e.g. from a database or api) or a manipulation of data (e.g. filtered, reduction, etc.)
type ApiQueryDatasource struct {
	union json.RawMessage
}

// ApiQueryFieldMeta defines model for ApiQueryFieldMeta.
type ApiQueryFieldMeta struct {
	CustomMetadata map[string]interface{} `json:"customMetadata,omitempty"`
	DataType       ApiMetricDataType      `json:"dataType"`
	Required       bool                   `json:"required"`
	Unit           string                 `json:"unit,omitempty"`
	Uri            string                 `json:"uri"`
}

// ApiQueryFieldValue defines model for ApiQueryFieldValue.
type ApiQueryFieldValue struct {
	union json.RawMessage
}

// ApiQueryFilter defines model for ApiQueryFilter.
type ApiQueryFilter struct {
	union json.RawMessage
}

// ApiQueryResult defines model for ApiQueryResult.
type ApiQueryResult struct {
	Data []ApiMeasurementValue `json:"data"`
	Meta ApiQueryFieldMeta     `json:"meta"`
}

// ApiRateFilter Rate filter computes the rate of change (delta / time_diff_in_seconds). Requires numeric, required field. Output is always decimal.
type ApiRateFilter struct {
	// MaxCounterValue Maximum counter value for wraparound detection. Only used when nonNegative is true. When set, counter resets compute delta as (maxCounterValue - previous + current).
	MaxCounterValue float64 `json:"maxCounterValue,omitempty"`

	// NonNegative When true, handles counter resets by clamping negative deltas. Decreases are treated as counter resets.
	NonNegative bool `json:"nonNegative,omitempty"`

	// OverrideUnit Unit for the rate output. If not specified, unit will be empty.
	OverrideUnit string `json:"overrideUnit,omitempty"`

	// PerSeconds Time period in seconds for rate calculation. Rate is computed as (delta / time_diff_seconds) * perSeconds. Default is 1 (per-second). Use 3600 for per-hour rate.
	PerSeconds *int              `json:"perSeconds,omitempty"`
	Type       ApiRateFilterType `json:"type"`
}

// ApiRateFilterType defines model for ApiRateFilter.Type.
type ApiRateFilterType string

// ApiReduceReportFieldValue Reduces multiple fields into a single value using a reduction function. If fieldUrns is not specified, all numeric fields are reduced.
type ApiReduceReportFieldValue struct {
	// FieldUrns URNs of fields to reduce. If not specified, all numeric fields are reduced.
	FieldUrns     []string                      `json:"fieldUrns,omitempty"`
	ReductionType ApiReductionType              `json:"reductionType"`
	Type          ApiReduceReportFieldValueType `json:"type"`
}

// ApiReduceReportFieldValueType defines model for ApiReduceReportFieldValue.Type.
type ApiReduceReportFieldValueType string

// ApiReductionQueryDatasource defines model for ApiReductionQueryDatasource.
type ApiReductionQueryDatasource struct {
	Aligner              ApiAlignerFilter    `json:"aligner"`
	EmptyDatasourceValue *ApiQueryFieldValue `json:"emptyDatasourceValue,omitempty"`
	FieldMeta            ApiAddFieldMeta     `json:"fieldMeta"`

	// MultiDatasource Multi Datasource is a collection of datasources, either static or a result of a dynamic query.
	MultiDatasource ApiMultiDatasource              `json:"multiDatasource"`
	ReductionType   ApiReductionType                `json:"reductionType"`
	Type            ApiReductionQueryDatasourceType `json:"type"`
}

// ApiReductionQueryDatasourceType defines model for ApiReductionQueryDatasource.Type.
type ApiReductionQueryDatasourceType string

// ApiReductionType defines model for ApiReductionType.
type ApiReductionType = tsquery.ReductionType

// ApiRefQueryFieldValue defines model for ApiRefQueryFieldValue.
type ApiRefQueryFieldValue struct {
	Type ApiRefQueryFieldValueType `json:"type"`
}

// ApiRefQueryFieldValueType defines model for ApiRefQueryFieldValue.Type.
type ApiRefQueryFieldValueType string

// ApiRefReportFieldValue Reference to a field in the report by its URN
type ApiRefReportFieldValue struct {
	Type ApiRefReportFieldValueType `json:"type"`
	Urn  string                     `json:"urn"`
}

// ApiRefReportFieldValueType defines model for ApiRefReportFieldValue.Type.
type ApiRefReportFieldValueType string

// ApiReportDatasource Report datasource that produces multiple fields per timestamp.
type ApiReportDatasource struct {
	union json.RawMessage
}

// ApiReportFieldValue defines model for ApiReportFieldValue.
type ApiReportFieldValue struct {
	union json.RawMessage
}

// ApiReportFilter Filter for report datasources.
type ApiReportFilter struct {
	union json.RawMessage
}

// ApiReportMeasurementRow A single row in a report with timestamp and values for all fields.
type ApiReportMeasurementRow struct {
	Timestamp time.Time `json:"timestamp"`

	// Values Values for each field, in the same order as fieldsMeta.
	Values []any `json:"values"`
}

// ApiReportMultiDatasource Multi datasource for reports - a collection of report datasources.
type ApiReportMultiDatasource struct {
	union json.RawMessage
}

// ApiSelectorQueryFieldValue defines model for ApiSelectorQueryFieldValue.
type ApiSelectorQueryFieldValue struct {
	FalseField           ApiQueryFieldValue             `json:"falseField"`
	SelectorBooleanField ApiQueryFieldValue             `json:"selectorBooleanField"`
	TrueField            ApiQueryFieldValue             `json:"trueField"`
	Type                 ApiSelectorQueryFieldValueType `json:"type"`
}

// ApiSelectorQueryFieldValueType defines model for ApiSelectorQueryFieldValue.Type.
type ApiSelectorQueryFieldValueType string

// ApiSelectorReportFieldValue defines model for ApiSelectorReportFieldValue.
type ApiSelectorReportFieldValue struct {
	FalseField           ApiReportFieldValue             `json:"falseField"`
	SelectorBooleanField ApiReportFieldValue             `json:"selectorBooleanField"`
	TrueField            ApiReportFieldValue             `json:"trueField"`
	Type                 ApiSelectorReportFieldValueType `json:"type"`
}

// ApiSelectorReportFieldValueType defines model for ApiSelectorReportFieldValue.Type.
type ApiSelectorReportFieldValueType string

// ApiSingleFieldReportFilter Replaces all fields with a single computed field. Maps to report.SingleFieldFilter.
type ApiSingleFieldReportFilter struct {
	FieldMeta  ApiAddFieldMeta                `json:"fieldMeta"`
	FieldValue ApiReportFieldValue            `json:"fieldValue"`
	Type       ApiSingleFieldReportFilterType `json:"type"`
}

// ApiSingleFieldReportFilterType defines model for ApiSingleFieldReportFilter.Type.
type ApiSingleFieldReportFilterType string

// ApiStaticQueryDatasource defines model for ApiStaticQueryDatasource.
type ApiStaticQueryDatasource struct {
	Data      []ApiMeasurementValue        `json:"data"`
	FieldMeta ApiQueryFieldMeta            `json:"fieldMeta"`
	Type      ApiStaticQueryDatasourceType `json:"type"`
}

// ApiStaticQueryDatasourceType defines model for ApiStaticQueryDatasource.Type.
type ApiStaticQueryDatasourceType string

// ApiStaticReportDatasource Static report datasource with predefined field metadata and data.
type ApiStaticReportDatasource struct {
	// Data Array of rows, where each row contains a timestamp and values for each field (in order of fieldsMeta).
	Data       []ApiReportMeasurementRow     `json:"data"`
	FieldsMeta []ApiQueryFieldMeta           `json:"fieldsMeta"`
	Type       ApiStaticReportDatasourceType `json:"type"`
}

// ApiStaticReportDatasourceType defines model for ApiStaticReportDatasource.Type.
type ApiStaticReportDatasourceType string

// ApiUnaryNumericOperatorQueryFieldValue defines model for ApiUnaryNumericOperatorQueryFieldValue.
type ApiUnaryNumericOperatorQueryFieldValue struct {
	Op      ApiUnaryNumericOperatorType                `json:"op"`
	Operand ApiQueryFieldValue                         `json:"operand"`
	Type    ApiUnaryNumericOperatorQueryFieldValueType `json:"type"`
}

// ApiUnaryNumericOperatorQueryFieldValueType defines model for ApiUnaryNumericOperatorQueryFieldValue.Type.
type ApiUnaryNumericOperatorQueryFieldValueType string

// ApiUnaryNumericOperatorReportFieldValue defines model for ApiUnaryNumericOperatorReportFieldValue.
type ApiUnaryNumericOperatorReportFieldValue struct {
	Op      ApiUnaryNumericOperatorType                 `json:"op"`
	Operand ApiReportFieldValue                         `json:"operand"`
	Type    ApiUnaryNumericOperatorReportFieldValueType `json:"type"`
}

// ApiUnaryNumericOperatorReportFieldValueType defines model for ApiUnaryNumericOperatorReportFieldValue.Type.
type ApiUnaryNumericOperatorReportFieldValueType string

// ApiUnaryNumericOperatorType defines model for ApiUnaryNumericOperatorType.
type ApiUnaryNumericOperatorType = tsquery.UnaryNumericOperatorType

// ExecuteQueryJSONRequestBody defines body for ExecuteQuery for application/json ContentType.
type ExecuteQueryJSONRequestBody = ApiExecuteQueryCommandArgs

// AsApiCalendarAlignmentPeriod returns the union data inside the ApiAlignmentPeriod as a ApiCalendarAlignmentPeriod
func (t ApiAlignmentPeriod) AsApiCalendarAlignmentPeriod() (ApiCalendarAlignmentPeriod, error) {
	var body ApiCalendarAlignmentPeriod
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiCalendarAlignmentPeriod overwrites any union data inside the ApiAlignmentPeriod as the provided ApiCalendarAlignmentPeriod
func (t *ApiAlignmentPeriod) FromApiCalendarAlignmentPeriod(v ApiCalendarAlignmentPeriod) error {
	v.Type = "calendar"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiCustomAlignmentPeriod returns the union data inside the ApiAlignmentPeriod as a ApiCustomAlignmentPeriod
func (t ApiAlignmentPeriod) AsApiCustomAlignmentPeriod() (ApiCustomAlignmentPeriod, error) {
	var body ApiCustomAlignmentPeriod
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiCustomAlignmentPeriod overwrites any union data inside the ApiAlignmentPeriod as the provided ApiCustomAlignmentPeriod
func (t *ApiAlignmentPeriod) FromApiCustomAlignmentPeriod(v ApiCustomAlignmentPeriod) error {
	v.Type = "custom"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


func (t ApiAlignmentPeriod) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ApiAlignmentPeriod) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "calendar":
		return t.AsApiCalendarAlignmentPeriod()
	case "custom":
		return t.AsApiCustomAlignmentPeriod()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ApiAlignmentPeriod) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ApiAlignmentPeriod) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsApiListMultiDatasource returns the union data inside the ApiMultiDatasource as a ApiListMultiDatasource
func (t ApiMultiDatasource) AsApiListMultiDatasource() (ApiListMultiDatasource, error) {
	var body ApiListMultiDatasource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiListMultiDatasource overwrites any union data inside the ApiMultiDatasource as the provided ApiListMultiDatasource
func (t *ApiMultiDatasource) FromApiListMultiDatasource(v ApiListMultiDatasource) error {
	v.Type = "list"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiFilteredMultiDatasource returns the union data inside the ApiMultiDatasource as a ApiFilteredMultiDatasource
func (t ApiMultiDatasource) AsApiFilteredMultiDatasource() (ApiFilteredMultiDatasource, error) {
	var body ApiFilteredMultiDatasource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiFilteredMultiDatasource overwrites any union data inside the ApiMultiDatasource as the provided ApiFilteredMultiDatasource
func (t *ApiMultiDatasource) FromApiFilteredMultiDatasource(v ApiFilteredMultiDatasource) error {
	v.Type = "filtered"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


func (t ApiMultiDatasource) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ApiMultiDatasource) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "filtered":
		return t.AsApiFilteredMultiDatasource()
	case "list":
		return t.AsApiListMultiDatasource()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ApiMultiDatasource) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ApiMultiDatasource) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsApiFilteredQueryDatasource returns the union data inside the ApiQueryDatasource as a ApiFilteredQueryDatasource
func (t ApiQueryDatasource) AsApiFilteredQueryDatasource() (ApiFilteredQueryDatasource, error) {
	var body ApiFilteredQueryDatasource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiFilteredQueryDatasource overwrites any union data inside the ApiQueryDatasource as the provided ApiFilteredQueryDatasource
func (t *ApiQueryDatasource) FromApiFilteredQueryDatasource(v ApiFilteredQueryDatasource) error {
	v.Type = "filtered"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiReductionQueryDatasource returns the union data inside the ApiQueryDatasource as a ApiReductionQueryDatasource
func (t ApiQueryDatasource) AsApiReductionQueryDatasource() (ApiReductionQueryDatasource, error) {
	var body ApiReductionQueryDatasource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiReductionQueryDatasource overwrites any union data inside the ApiQueryDatasource as the provided ApiReductionQueryDatasource
func (t *ApiQueryDatasource) FromApiReductionQueryDatasource(v ApiReductionQueryDatasource) error {
	v.Type = "reduction"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiStaticQueryDatasource returns the union data inside the ApiQueryDatasource as a ApiStaticQueryDatasource
func (t ApiQueryDatasource) AsApiStaticQueryDatasource() (ApiStaticQueryDatasource, error) {
	var body ApiStaticQueryDatasource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiStaticQueryDatasource overwrites any union data inside the ApiQueryDatasource as the provided ApiStaticQueryDatasource
func (t *ApiQueryDatasource) FromApiStaticQueryDatasource(v ApiStaticQueryDatasource) error {
	v.Type = "static"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiFromReportQueryDatasource returns the union data inside the ApiQueryDatasource as a ApiFromReportQueryDatasource
func (t ApiQueryDatasource) AsApiFromReportQueryDatasource() (ApiFromReportQueryDatasource, error) {
	var body ApiFromReportQueryDatasource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiFromReportQueryDatasource overwrites any union data inside the ApiQueryDatasource as the provided ApiFromReportQueryDatasource
func (t *ApiQueryDatasource) FromApiFromReportQueryDatasource(v ApiFromReportQueryDatasource) error {
	v.Type = "fromReport"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


func (t ApiQueryDatasource) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ApiQueryDatasource) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "filtered":
		return t.AsApiFilteredQueryDatasource()
	case "fromReport":
		return t.AsApiFromReportQueryDatasource()
	case "reduction":
		return t.AsApiReductionQueryDatasource()
	case "static":
		return t.AsApiStaticQueryDatasource()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ApiQueryDatasource) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ApiQueryDatasource) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsApiConstantQueryFieldValue returns the union data inside the ApiQueryFieldValue as a ApiConstantQueryFieldValue
func (t ApiQueryFieldValue) AsApiConstantQueryFieldValue() (ApiConstantQueryFieldValue, error) {
	var body ApiConstantQueryFieldValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiConstantQueryFieldValue overwrites any union data inside the ApiQueryFieldValue as the provided ApiConstantQueryFieldValue
func (t *ApiQueryFieldValue) FromApiConstantQueryFieldValue(v ApiConstantQueryFieldValue) error {
	v.Type = "constant"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiConditionQueryFieldValue returns the union data inside the ApiQueryFieldValue as a ApiConditionQueryFieldValue
func (t ApiQueryFieldValue) AsApiConditionQueryFieldValue() (ApiConditionQueryFieldValue, error) {
	var body ApiConditionQueryFieldValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiConditionQueryFieldValue overwrites any union data inside the ApiQueryFieldValue as the provided ApiConditionQueryFieldValue
func (t *ApiQueryFieldValue) FromApiConditionQueryFieldValue(v ApiConditionQueryFieldValue) error {
	v.Type = "condition"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiLogicalExpressionQueryFieldValue returns the union data inside the ApiQueryFieldValue as a ApiLogicalExpressionQueryFieldValue
func (t ApiQueryFieldValue) AsApiLogicalExpressionQueryFieldValue() (ApiLogicalExpressionQueryFieldValue, error) {
	var body ApiLogicalExpressionQueryFieldValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiLogicalExpressionQueryFieldValue overwrites any union data inside the ApiQueryFieldValue as the provided ApiLogicalExpressionQueryFieldValue
func (t *ApiQueryFieldValue) FromApiLogicalExpressionQueryFieldValue(v ApiLogicalExpressionQueryFieldValue) error {
	v.Type = "logicalExpression"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiRefQueryFieldValue returns the union data inside the ApiQueryFieldValue as a ApiRefQueryFieldValue
func (t ApiQueryFieldValue) AsApiRefQueryFieldValue() (ApiRefQueryFieldValue, error) {
	var body ApiRefQueryFieldValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiRefQueryFieldValue overwrites any union data inside the ApiQueryFieldValue as the provided ApiRefQueryFieldValue
func (t *ApiQueryFieldValue) FromApiRefQueryFieldValue(v ApiRefQueryFieldValue) error {
	v.Type = "ref"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiSelectorQueryFieldValue returns the union data inside the ApiQueryFieldValue as a ApiSelectorQueryFieldValue
func (t ApiQueryFieldValue) AsApiSelectorQueryFieldValue() (ApiSelectorQueryFieldValue, error) {
	var body ApiSelectorQueryFieldValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiSelectorQueryFieldValue overwrites any union data inside the ApiQueryFieldValue as the provided ApiSelectorQueryFieldValue
func (t *ApiQueryFieldValue) FromApiSelectorQueryFieldValue(v ApiSelectorQueryFieldValue) error {
	v.Type = "selector"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiNvlQueryFieldValue returns the union data inside the ApiQueryFieldValue as a ApiNvlQueryFieldValue
func (t ApiQueryFieldValue) AsApiNvlQueryFieldValue() (ApiNvlQueryFieldValue, error) {
	var body ApiNvlQueryFieldValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiNvlQueryFieldValue overwrites any union data inside the ApiQueryFieldValue as the provided ApiNvlQueryFieldValue
func (t *ApiQueryFieldValue) FromApiNvlQueryFieldValue(v ApiNvlQueryFieldValue) error {
	v.Type = "nvl"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiCastQueryFieldValue returns the union data inside the ApiQueryFieldValue as a ApiCastQueryFieldValue
func (t ApiQueryFieldValue) AsApiCastQueryFieldValue() (ApiCastQueryFieldValue, error) {
	var body ApiCastQueryFieldValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiCastQueryFieldValue overwrites any union data inside the ApiQueryFieldValue as the provided ApiCastQueryFieldValue
func (t *ApiQueryFieldValue) FromApiCastQueryFieldValue(v ApiCastQueryFieldValue) error {
	v.Type = "cast"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiNumericExpressionQueryFieldValue returns the union data inside the ApiQueryFieldValue as a ApiNumericExpressionQueryFieldValue
func (t ApiQueryFieldValue) AsApiNumericExpressionQueryFieldValue() (ApiNumericExpressionQueryFieldValue, error) {
	var body ApiNumericExpressionQueryFieldValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiNumericExpressionQueryFieldValue overwrites any union data inside the ApiQueryFieldValue as the provided ApiNumericExpressionQueryFieldValue
func (t *ApiQueryFieldValue) FromApiNumericExpressionQueryFieldValue(v ApiNumericExpressionQueryFieldValue) error {
	v.Type = "numericExpression"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiUnaryNumericOperatorQueryFieldValue returns the union data inside the ApiQueryFieldValue as a ApiUnaryNumericOperatorQueryFieldValue
func (t ApiQueryFieldValue) AsApiUnaryNumericOperatorQueryFieldValue() (ApiUnaryNumericOperatorQueryFieldValue, error) {
	var body ApiUnaryNumericOperatorQueryFieldValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiUnaryNumericOperatorQueryFieldValue overwrites any union data inside the ApiQueryFieldValue as the provided ApiUnaryNumericOperatorQueryFieldValue
func (t *ApiQueryFieldValue) FromApiUnaryNumericOperatorQueryFieldValue(v ApiUnaryNumericOperatorQueryFieldValue) error {
	v.Type = "unaryNumericOperator"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiNilQueryFieldValue returns the union data inside the ApiQueryFieldValue as a ApiNilQueryFieldValue
func (t ApiQueryFieldValue) AsApiNilQueryFieldValue() (ApiNilQueryFieldValue, error) {
	var body ApiNilQueryFieldValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiNilQueryFieldValue overwrites any union data inside the ApiQueryFieldValue as the provided ApiNilQueryFieldValue
func (t *ApiQueryFieldValue) FromApiNilQueryFieldValue(v ApiNilQueryFieldValue) error {
	v.Type = "nil"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


func (t ApiQueryFieldValue) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ApiQueryFieldValue) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "cast":
		return t.AsApiCastQueryFieldValue()
	case "condition":
		return t.AsApiConditionQueryFieldValue()
	case "constant":
		return t.AsApiConstantQueryFieldValue()
	case "logicalExpression":
		return t.AsApiLogicalExpressionQueryFieldValue()
	case "nil":
		return t.AsApiNilQueryFieldValue()
	case "numericExpression":
		return t.AsApiNumericExpressionQueryFieldValue()
	case "nvl":
		return t.AsApiNvlQueryFieldValue()
	case "ref":
		return t.AsApiRefQueryFieldValue()
	case "selector":
		return t.AsApiSelectorQueryFieldValue()
	case "unaryNumericOperator":
		return t.AsApiUnaryNumericOperatorQueryFieldValue()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ApiQueryFieldValue) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ApiQueryFieldValue) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsApiAlignerFilter returns the union data inside the ApiQueryFilter as a ApiAlignerFilter
func (t ApiQueryFilter) AsApiAlignerFilter() (ApiAlignerFilter, error) {
	var body ApiAlignerFilter
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiAlignerFilter overwrites any union data inside the ApiQueryFilter as the provided ApiAlignerFilter
func (t *ApiQueryFilter) FromApiAlignerFilter(v ApiAlignerFilter) error {
	v.Type = "aligner"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiConditionFilter returns the union data inside the ApiQueryFilter as a ApiConditionFilter
func (t ApiQueryFilter) AsApiConditionFilter() (ApiConditionFilter, error) {
	var body ApiConditionFilter
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiConditionFilter overwrites any union data inside the ApiQueryFilter as the provided ApiConditionFilter
func (t *ApiQueryFilter) FromApiConditionFilter(v ApiConditionFilter) error {
	v.Type = "condition"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiFieldValueFilter returns the union data inside the ApiQueryFilter as a ApiFieldValueFilter
func (t ApiQueryFilter) AsApiFieldValueFilter() (ApiFieldValueFilter, error) {
	var body ApiFieldValueFilter
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiFieldValueFilter overwrites any union data inside the ApiQueryFilter as the provided ApiFieldValueFilter
func (t *ApiQueryFilter) FromApiFieldValueFilter(v ApiFieldValueFilter) error {
	v.Type = "fieldValue"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiOverrideFieldMetadataFilter returns the union data inside the ApiQueryFilter as a ApiOverrideFieldMetadataFilter
func (t ApiQueryFilter) AsApiOverrideFieldMetadataFilter() (ApiOverrideFieldMetadataFilter, error) {
	var body ApiOverrideFieldMetadataFilter
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiOverrideFieldMetadataFilter overwrites any union data inside the ApiQueryFilter as the provided ApiOverrideFieldMetadataFilter
func (t *ApiQueryFilter) FromApiOverrideFieldMetadataFilter(v ApiOverrideFieldMetadataFilter) error {
	v.Type = "overrideFieldMetadata"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiDeltaFilter returns the union data inside the ApiQueryFilter as a ApiDeltaFilter
func (t ApiQueryFilter) AsApiDeltaFilter() (ApiDeltaFilter, error) {
	var body ApiDeltaFilter
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiDeltaFilter overwrites any union data inside the ApiQueryFilter as the provided ApiDeltaFilter
func (t *ApiQueryFilter) FromApiDeltaFilter(v ApiDeltaFilter) error {
	v.Type = "delta"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiRateFilter returns the union data inside the ApiQueryFilter as a ApiRateFilter
func (t ApiQueryFilter) AsApiRateFilter() (ApiRateFilter, error) {
	var body ApiRateFilter
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiRateFilter overwrites any union data inside the ApiQueryFilter as the provided ApiRateFilter
func (t *ApiQueryFilter) FromApiRateFilter(v ApiRateFilter) error {
	v.Type = "rate"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


func (t ApiQueryFilter) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ApiQueryFilter) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "aligner":
		return t.AsApiAlignerFilter()
	case "condition":
		return t.AsApiConditionFilter()
	case "delta":
		return t.AsApiDeltaFilter()
	case "fieldValue":
		return t.AsApiFieldValueFilter()
	case "overrideFieldMetadata":
		return t.AsApiOverrideFieldMetadataFilter()
	case "rate":
		return t.AsApiRateFilter()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ApiQueryFilter) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ApiQueryFilter) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsApiStaticReportDatasource returns the union data inside the ApiReportDatasource as a ApiStaticReportDatasource
func (t ApiReportDatasource) AsApiStaticReportDatasource() (ApiStaticReportDatasource, error) {
	var body ApiStaticReportDatasource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiStaticReportDatasource overwrites any union data inside the ApiReportDatasource as the provided ApiStaticReportDatasource
func (t *ApiReportDatasource) FromApiStaticReportDatasource(v ApiStaticReportDatasource) error {
	v.Type = "static"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiJoinReportDatasource returns the union data inside the ApiReportDatasource as a ApiJoinReportDatasource
func (t ApiReportDatasource) AsApiJoinReportDatasource() (ApiJoinReportDatasource, error) {
	var body ApiJoinReportDatasource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiJoinReportDatasource overwrites any union data inside the ApiReportDatasource as the provided ApiJoinReportDatasource
func (t *ApiReportDatasource) FromApiJoinReportDatasource(v ApiJoinReportDatasource) error {
	v.Type = "join"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiFromDatasourceReportDatasource returns the union data inside the ApiReportDatasource as a ApiFromDatasourceReportDatasource
func (t ApiReportDatasource) AsApiFromDatasourceReportDatasource() (ApiFromDatasourceReportDatasource, error) {
	var body ApiFromDatasourceReportDatasource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiFromDatasourceReportDatasource overwrites any union data inside the ApiReportDatasource as the provided ApiFromDatasourceReportDatasource
func (t *ApiReportDatasource) FromApiFromDatasourceReportDatasource(v ApiFromDatasourceReportDatasource) error {
	v.Type = "fromDatasource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiFilteredReportDatasource returns the union data inside the ApiReportDatasource as a ApiFilteredReportDatasource
func (t ApiReportDatasource) AsApiFilteredReportDatasource() (ApiFilteredReportDatasource, error) {
	var body ApiFilteredReportDatasource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiFilteredReportDatasource overwrites any union data inside the ApiReportDatasource as the provided ApiFilteredReportDatasource
func (t *ApiReportDatasource) FromApiFilteredReportDatasource(v ApiFilteredReportDatasource) error {
	v.Type = "filtered"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


func (t ApiReportDatasource) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ApiReportDatasource) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "filtered":
		return t.AsApiFilteredReportDatasource()
	case "fromDatasource":
		return t.AsApiFromDatasourceReportDatasource()
	case "join":
		return t.AsApiJoinReportDatasource()
	case "static":
		return t.AsApiStaticReportDatasource()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ApiReportDatasource) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ApiReportDatasource) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsApiConstantReportFieldValue returns the union data inside the ApiReportFieldValue as a ApiConstantReportFieldValue
func (t ApiReportFieldValue) AsApiConstantReportFieldValue() (ApiConstantReportFieldValue, error) {
	var body ApiConstantReportFieldValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiConstantReportFieldValue overwrites any union data inside the ApiReportFieldValue as the provided ApiConstantReportFieldValue
func (t *ApiReportFieldValue) FromApiConstantReportFieldValue(v ApiConstantReportFieldValue) error {
	v.Type = "constant"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiConditionReportFieldValue returns the union data inside the ApiReportFieldValue as a ApiConditionReportFieldValue
func (t ApiReportFieldValue) AsApiConditionReportFieldValue() (ApiConditionReportFieldValue, error) {
	var body ApiConditionReportFieldValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiConditionReportFieldValue overwrites any union data inside the ApiReportFieldValue as the provided ApiConditionReportFieldValue
func (t *ApiReportFieldValue) FromApiConditionReportFieldValue(v ApiConditionReportFieldValue) error {
	v.Type = "condition"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiLogicalExpressionReportFieldValue returns the union data inside the ApiReportFieldValue as a ApiLogicalExpressionReportFieldValue
func (t ApiReportFieldValue) AsApiLogicalExpressionReportFieldValue() (ApiLogicalExpressionReportFieldValue, error) {
	var body ApiLogicalExpressionReportFieldValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiLogicalExpressionReportFieldValue overwrites any union data inside the ApiReportFieldValue as the provided ApiLogicalExpressionReportFieldValue
func (t *ApiReportFieldValue) FromApiLogicalExpressionReportFieldValue(v ApiLogicalExpressionReportFieldValue) error {
	v.Type = "logicalExpression"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiRefReportFieldValue returns the union data inside the ApiReportFieldValue as a ApiRefReportFieldValue
func (t ApiReportFieldValue) AsApiRefReportFieldValue() (ApiRefReportFieldValue, error) {
	var body ApiRefReportFieldValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiRefReportFieldValue overwrites any union data inside the ApiReportFieldValue as the provided ApiRefReportFieldValue
func (t *ApiReportFieldValue) FromApiRefReportFieldValue(v ApiRefReportFieldValue) error {
	v.Type = "ref"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiSelectorReportFieldValue returns the union data inside the ApiReportFieldValue as a ApiSelectorReportFieldValue
func (t ApiReportFieldValue) AsApiSelectorReportFieldValue() (ApiSelectorReportFieldValue, error) {
	var body ApiSelectorReportFieldValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiSelectorReportFieldValue overwrites any union data inside the ApiReportFieldValue as the provided ApiSelectorReportFieldValue
func (t *ApiReportFieldValue) FromApiSelectorReportFieldValue(v ApiSelectorReportFieldValue) error {
	v.Type = "selector"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiNvlReportFieldValue returns the union data inside the ApiReportFieldValue as a ApiNvlReportFieldValue
func (t ApiReportFieldValue) AsApiNvlReportFieldValue() (ApiNvlReportFieldValue, error) {
	var body ApiNvlReportFieldValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiNvlReportFieldValue overwrites any union data inside the ApiReportFieldValue as the provided ApiNvlReportFieldValue
func (t *ApiReportFieldValue) FromApiNvlReportFieldValue(v ApiNvlReportFieldValue) error {
	v.Type = "nvl"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiCastReportFieldValue returns the union data inside the ApiReportFieldValue as a ApiCastReportFieldValue
func (t ApiReportFieldValue) AsApiCastReportFieldValue() (ApiCastReportFieldValue, error) {
	var body ApiCastReportFieldValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiCastReportFieldValue overwrites any union data inside the ApiReportFieldValue as the provided ApiCastReportFieldValue
func (t *ApiReportFieldValue) FromApiCastReportFieldValue(v ApiCastReportFieldValue) error {
	v.Type = "cast"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiNumericExpressionReportFieldValue returns the union data inside the ApiReportFieldValue as a ApiNumericExpressionReportFieldValue
func (t ApiReportFieldValue) AsApiNumericExpressionReportFieldValue() (ApiNumericExpressionReportFieldValue, error) {
	var body ApiNumericExpressionReportFieldValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiNumericExpressionReportFieldValue overwrites any union data inside the ApiReportFieldValue as the provided ApiNumericExpressionReportFieldValue
func (t *ApiReportFieldValue) FromApiNumericExpressionReportFieldValue(v ApiNumericExpressionReportFieldValue) error {
	v.Type = "numericExpression"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiUnaryNumericOperatorReportFieldValue returns the union data inside the ApiReportFieldValue as a ApiUnaryNumericOperatorReportFieldValue
func (t ApiReportFieldValue) AsApiUnaryNumericOperatorReportFieldValue() (ApiUnaryNumericOperatorReportFieldValue, error) {
	var body ApiUnaryNumericOperatorReportFieldValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiUnaryNumericOperatorReportFieldValue overwrites any union data inside the ApiReportFieldValue as the provided ApiUnaryNumericOperatorReportFieldValue
func (t *ApiReportFieldValue) FromApiUnaryNumericOperatorReportFieldValue(v ApiUnaryNumericOperatorReportFieldValue) error {
	v.Type = "unaryNumericOperator"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiReduceReportFieldValue returns the union data inside the ApiReportFieldValue as a ApiReduceReportFieldValue
func (t ApiReportFieldValue) AsApiReduceReportFieldValue() (ApiReduceReportFieldValue, error) {
	var body ApiReduceReportFieldValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiReduceReportFieldValue overwrites any union data inside the ApiReportFieldValue as the provided ApiReduceReportFieldValue
func (t *ApiReportFieldValue) FromApiReduceReportFieldValue(v ApiReduceReportFieldValue) error {
	v.Type = "reduce"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiNilReportFieldValue returns the union data inside the ApiReportFieldValue as a ApiNilReportFieldValue
func (t ApiReportFieldValue) AsApiNilReportFieldValue() (ApiNilReportFieldValue, error) {
	var body ApiNilReportFieldValue
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiNilReportFieldValue overwrites any union data inside the ApiReportFieldValue as the provided ApiNilReportFieldValue
func (t *ApiReportFieldValue) FromApiNilReportFieldValue(v ApiNilReportFieldValue) error {
	v.Type = "nil"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


func (t ApiReportFieldValue) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ApiReportFieldValue) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "cast":
		return t.AsApiCastReportFieldValue()
	case "condition":
		return t.AsApiConditionReportFieldValue()
	case "constant":
		return t.AsApiConstantReportFieldValue()
	case "logicalExpression":
		return t.AsApiLogicalExpressionReportFieldValue()
	case "nil":
		return t.AsApiNilReportFieldValue()
	case "numericExpression":
		return t.AsApiNumericExpressionReportFieldValue()
	case "nvl":
		return t.AsApiNvlReportFieldValue()
	case "reduce":
		return t.AsApiReduceReportFieldValue()
	case "ref":
		return t.AsApiRefReportFieldValue()
	case "selector":
		return t.AsApiSelectorReportFieldValue()
	case "unaryNumericOperator":
		return t.AsApiUnaryNumericOperatorReportFieldValue()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ApiReportFieldValue) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ApiReportFieldValue) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsApiAlignerFilter returns the union data inside the ApiReportFilter as a ApiAlignerFilter
func (t ApiReportFilter) AsApiAlignerFilter() (ApiAlignerFilter, error) {
	var body ApiAlignerFilter
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiAlignerFilter overwrites any union data inside the ApiReportFilter as the provided ApiAlignerFilter
func (t *ApiReportFilter) FromApiAlignerFilter(v ApiAlignerFilter) error {
	v.Type = "aligner"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiConditionReportFilter returns the union data inside the ApiReportFilter as a ApiConditionReportFilter
func (t ApiReportFilter) AsApiConditionReportFilter() (ApiConditionReportFilter, error) {
	var body ApiConditionReportFilter
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiConditionReportFilter overwrites any union data inside the ApiReportFilter as the provided ApiConditionReportFilter
func (t *ApiReportFilter) FromApiConditionReportFilter(v ApiConditionReportFilter) error {
	v.Type = "condition"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiAppendFieldReportFilter returns the union data inside the ApiReportFilter as a ApiAppendFieldReportFilter
func (t ApiReportFilter) AsApiAppendFieldReportFilter() (ApiAppendFieldReportFilter, error) {
	var body ApiAppendFieldReportFilter
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiAppendFieldReportFilter overwrites any union data inside the ApiReportFilter as the provided ApiAppendFieldReportFilter
func (t *ApiReportFilter) FromApiAppendFieldReportFilter(v ApiAppendFieldReportFilter) error {
	v.Type = "appendField"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiDropFieldsReportFilter returns the union data inside the ApiReportFilter as a ApiDropFieldsReportFilter
func (t ApiReportFilter) AsApiDropFieldsReportFilter() (ApiDropFieldsReportFilter, error) {
	var body ApiDropFieldsReportFilter
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiDropFieldsReportFilter overwrites any union data inside the ApiReportFilter as the provided ApiDropFieldsReportFilter
func (t *ApiReportFilter) FromApiDropFieldsReportFilter(v ApiDropFieldsReportFilter) error {
	v.Type = "dropFields"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiSingleFieldReportFilter returns the union data inside the ApiReportFilter as a ApiSingleFieldReportFilter
func (t ApiReportFilter) AsApiSingleFieldReportFilter() (ApiSingleFieldReportFilter, error) {
	var body ApiSingleFieldReportFilter
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiSingleFieldReportFilter overwrites any union data inside the ApiReportFilter as the provided ApiSingleFieldReportFilter
func (t *ApiReportFilter) FromApiSingleFieldReportFilter(v ApiSingleFieldReportFilter) error {
	v.Type = "singleField"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiProjectionReportFilter returns the union data inside the ApiReportFilter as a ApiProjectionReportFilter
func (t ApiReportFilter) AsApiProjectionReportFilter() (ApiProjectionReportFilter, error) {
	var body ApiProjectionReportFilter
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiProjectionReportFilter overwrites any union data inside the ApiReportFilter as the provided ApiProjectionReportFilter
func (t *ApiReportFilter) FromApiProjectionReportFilter(v ApiProjectionReportFilter) error {
	v.Type = "projection"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


func (t ApiReportFilter) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ApiReportFilter) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "aligner":
		return t.AsApiAlignerFilter()
	case "appendField":
		return t.AsApiAppendFieldReportFilter()
	case "condition":
		return t.AsApiConditionReportFilter()
	case "dropFields":
		return t.AsApiDropFieldsReportFilter()
	case "projection":
		return t.AsApiProjectionReportFilter()
	case "singleField":
		return t.AsApiSingleFieldReportFilter()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ApiReportFilter) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ApiReportFilter) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsApiListReportMultiDatasource returns the union data inside the ApiReportMultiDatasource as a ApiListReportMultiDatasource
func (t ApiReportMultiDatasource) AsApiListReportMultiDatasource() (ApiListReportMultiDatasource, error) {
	var body ApiListReportMultiDatasource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiListReportMultiDatasource overwrites any union data inside the ApiReportMultiDatasource as the provided ApiListReportMultiDatasource
func (t *ApiReportMultiDatasource) FromApiListReportMultiDatasource(v ApiListReportMultiDatasource) error {
	v.Type = "list"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiFromMultiDatasourceReportMultiDatasource returns the union data inside the ApiReportMultiDatasource as a ApiFromMultiDatasourceReportMultiDatasource
func (t ApiReportMultiDatasource) AsApiFromMultiDatasourceReportMultiDatasource() (ApiFromMultiDatasourceReportMultiDatasource, error) {
	var body ApiFromMultiDatasourceReportMultiDatasource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiFromMultiDatasourceReportMultiDatasource overwrites any union data inside the ApiReportMultiDatasource as the provided ApiFromMultiDatasourceReportMultiDatasource
func (t *ApiReportMultiDatasource) FromApiFromMultiDatasourceReportMultiDatasource(v ApiFromMultiDatasourceReportMultiDatasource) error {
	v.Type = "fromMultiDatasource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


// AsApiFilteredReportMultiDatasource returns the union data inside the ApiReportMultiDatasource as a ApiFilteredReportMultiDatasource
func (t ApiReportMultiDatasource) AsApiFilteredReportMultiDatasource() (ApiFilteredReportMultiDatasource, error) {
	var body ApiFilteredReportMultiDatasource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiFilteredReportMultiDatasource overwrites any union data inside the ApiReportMultiDatasource as the provided ApiFilteredReportMultiDatasource
func (t *ApiReportMultiDatasource) FromApiFilteredReportMultiDatasource(v ApiFilteredReportMultiDatasource) error {
	v.Type = "filtered"
	b, err := json.Marshal(v)
	t.union = b
	return err
}


func (t ApiReportMultiDatasource) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ApiReportMultiDatasource) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "filtered":
		return t.AsApiFilteredReportMultiDatasource()
	case "fromMultiDatasource":
		return t.AsApiFromMultiDatasourceReportMultiDatasource()
	case "list":
		return t.AsApiListReportMultiDatasource()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ApiReportMultiDatasource) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ApiReportMultiDatasource) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
