// Package queryopenapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package queryopenapi

import (
	"encoding/json"
	"errors"
	"time"

	"github.com/shpandrak/shpanstream/utils/timeseries/tsquery"
	"github.com/shpandrak/shpanstream/utils/timeseries/tsquery/field"
)

// Defines values for ApiAlignerFilterType.
const (
	Aligner ApiAlignerFilterType = "aligner"
)

// Defines values for ApiAlignerFunction.
const (
	Avg   ApiAlignerFunction = "avg"
	Count ApiAlignerFunction = "count"
	Max   ApiAlignerFunction = "max"
	Min   ApiAlignerFunction = "min"
	Sum   ApiAlignerFunction = "sum"
)

// Defines values for ApiAppendFieldFilterType.
const (
	AppendField ApiAppendFieldFilterType = "appendField"
)

// Defines values for ApiCalendarAlignmentPeriodType.
const (
	Calendar ApiCalendarAlignmentPeriodType = "calendar"
)

// Defines values for ApiCalendarPeriodType.
const (
	Day         ApiCalendarPeriodType = "day"
	HalfYear    ApiCalendarPeriodType = "halfYear"
	Hour        ApiCalendarPeriodType = "hour"
	Month       ApiCalendarPeriodType = "month"
	Quarter     ApiCalendarPeriodType = "quarter"
	QuarterHour ApiCalendarPeriodType = "quarterHour"
	Week        ApiCalendarPeriodType = "week"
	Year        ApiCalendarPeriodType = "year"
)

// Defines values for ApiCastQueryFieldType.
const (
	Cast ApiCastQueryFieldType = "cast"
)

// Defines values for ApiConditionFilterType.
const (
	ApiConditionFilterTypeCondition ApiConditionFilterType = "condition"
)

// Defines values for ApiConditionQueryFieldType.
const (
	ApiConditionQueryFieldTypeCondition ApiConditionQueryFieldType = "condition"
)

// Defines values for ApiConstantQueryFieldType.
const (
	Constant ApiConstantQueryFieldType = "constant"
)

// Defines values for ApiCustomAlignmentPeriodType.
const (
	Custom ApiCustomAlignmentPeriodType = "custom"
)

// Defines values for ApiDropFieldFilterType.
const (
	DropField ApiDropFieldFilterType = "dropField"
)

// Defines values for ApiFilteredQueryDatasourceType.
const (
	Filtered ApiFilteredQueryDatasourceType = "filtered"
)

// Defines values for ApiJoinQueryDatasourceJoinType.
const (
	Full  ApiJoinQueryDatasourceJoinType = "full"
	Inner ApiJoinQueryDatasourceJoinType = "inner"
	Left  ApiJoinQueryDatasourceJoinType = "left"
)

// Defines values for ApiJoinQueryDatasourceType.
const (
	Join ApiJoinQueryDatasourceType = "join"
)

// Defines values for ApiLogicalExpressionQueryFieldType.
const (
	LogicalExpression ApiLogicalExpressionQueryFieldType = "logicalExpression"
)

// Defines values for ApiNumericExpressionQueryFieldType.
const (
	NumericExpression ApiNumericExpressionQueryFieldType = "numericExpression"
)

// Defines values for ApiNvlQueryFieldType.
const (
	Nvl ApiNvlQueryFieldType = "nvl"
)

// Defines values for ApiOverrideFieldMetadataFilterType.
const (
	OverrideFieldMetadata ApiOverrideFieldMetadataFilterType = "overrideFieldMetadata"
)

// Defines values for ApiRawQueryDatasourceType.
const (
	Raw ApiRawQueryDatasourceType = "raw"
)

// Defines values for ApiReduceQueryFieldType.
const (
	Reduce ApiReduceQueryFieldType = "reduce"
)

// Defines values for ApiRefQueryFieldType.
const (
	Ref ApiRefQueryFieldType = "ref"
)

// Defines values for ApiReplaceFieldFilterType.
const (
	ReplaceField ApiReplaceFieldFilterType = "replaceField"
)

// Defines values for ApiSelectorQueryFieldType.
const (
	Selector ApiSelectorQueryFieldType = "selector"
)

// Defines values for ApiSingleFieldFilterType.
const (
	SingleField ApiSingleFieldFilterType = "singleField"
)

// Defines values for ApiStaticQueryDatasourceType.
const (
	Static ApiStaticQueryDatasourceType = "static"
)

// Defines values for ApiUnaryNumericOperatorQueryFieldType.
const (
	UnaryNumericOperator ApiUnaryNumericOperatorQueryFieldType = "unaryNumericOperator"
)

// ApiAlignerFilter defines model for ApiAlignerFilter.
type ApiAlignerFilter struct {
	AlignerPeriod     ApiAlignmentPeriod   `json:"alignerPeriod"`
	AlignmentFunction ApiAlignerFunction   `json:"alignmentFunction"`
	Type              ApiAlignerFilterType `json:"type"`
}

// ApiAlignerFilterType defines model for ApiAlignerFilter.Type.
type ApiAlignerFilterType string

// ApiAlignerFunction defines model for ApiAlignerFunction.
type ApiAlignerFunction string

// ApiAlignmentPeriod defines model for ApiAlignmentPeriod.
type ApiAlignmentPeriod struct {
	union json.RawMessage
}

// ApiAppendFieldFilter defines model for ApiAppendFieldFilter.
type ApiAppendFieldFilter struct {
	Field ApiQueryField            `json:"field"`
	Type  ApiAppendFieldFilterType `json:"type"`
}

// ApiAppendFieldFilterType defines model for ApiAppendFieldFilter.Type.
type ApiAppendFieldFilterType string

// ApiBinaryNumericOperatorType defines model for ApiBinaryNumericOperatorType.
type ApiBinaryNumericOperatorType = field.BinaryNumericOperatorType

// ApiCalendarAlignmentPeriod defines model for ApiCalendarAlignmentPeriod.
type ApiCalendarAlignmentPeriod struct {
	AlignmentPeriodType ApiCalendarPeriodType          `json:"alignmentPeriodType"`
	Type                ApiCalendarAlignmentPeriodType `json:"type"`
	ZoneId              string                         `json:"zoneId"`
}

// ApiCalendarAlignmentPeriodType defines model for ApiCalendarAlignmentPeriod.Type.
type ApiCalendarAlignmentPeriodType string

// ApiCalendarPeriodType defines model for ApiCalendarPeriodType.
type ApiCalendarPeriodType string

// ApiCastQueryField defines model for ApiCastQueryField.
type ApiCastQueryField struct {
	FieldUrn   string                `json:"fieldUrn"`
	Source     ApiQueryField         `json:"source"`
	TargetType ApiMetricDataType     `json:"targetType"`
	Type       ApiCastQueryFieldType `json:"type"`
}

// ApiCastQueryFieldType defines model for ApiCastQueryField.Type.
type ApiCastQueryFieldType string

// ApiConditionFilter defines model for ApiConditionFilter.
type ApiConditionFilter struct {
	BooleanField ApiQueryField          `json:"booleanField"`
	Type         ApiConditionFilterType `json:"type"`
}

// ApiConditionFilterType defines model for ApiConditionFilter.Type.
type ApiConditionFilterType string

// ApiConditionOperatorType defines model for ApiConditionOperatorType.
type ApiConditionOperatorType = field.ConditionOperatorType

// ApiConditionQueryField defines model for ApiConditionQueryField.
type ApiConditionQueryField struct {
	Operand1     ApiQueryField              `json:"operand1"`
	Operand2     ApiQueryField              `json:"operand2"`
	OperatorType ApiConditionOperatorType   `json:"operatorType"`
	Type         ApiConditionQueryFieldType `json:"type"`
	Urn          string                     `json:"urn"`
}

// ApiConditionQueryFieldType defines model for ApiConditionQueryField.Type.
type ApiConditionQueryFieldType string

// ApiConstantQueryField defines model for ApiConstantQueryField.
type ApiConstantQueryField struct {
	FieldMeta  ApiQueryFieldMeta         `json:"fieldMeta"`
	FieldValue any                       `json:"fieldValue"`
	Type       ApiConstantQueryFieldType `json:"type"`
}

// ApiConstantQueryFieldType defines model for ApiConstantQueryField.Type.
type ApiConstantQueryFieldType string

// ApiCustomAlignmentPeriod defines model for ApiCustomAlignmentPeriod.
type ApiCustomAlignmentPeriod struct {
	DurationInMillis int64                        `json:"durationInMillis"`
	Type             ApiCustomAlignmentPeriodType `json:"type"`
	ZoneId           string                       `json:"zoneId"`
}

// ApiCustomAlignmentPeriodType defines model for ApiCustomAlignmentPeriod.Type.
type ApiCustomAlignmentPeriodType string

// ApiDropFieldFilter defines model for ApiDropFieldFilter.
type ApiDropFieldFilter struct {
	FieldUrns []string               `json:"fieldUrns"`
	Type      ApiDropFieldFilterType `json:"type"`
}

// ApiDropFieldFilterType defines model for ApiDropFieldFilter.Type.
type ApiDropFieldFilterType string

// ApiExecuteQueryCommandArgs defines model for ApiExecuteQueryCommandArgs.
type ApiExecuteQueryCommandArgs struct {
	Datasource ApiFilteredQueryDatasource `json:"datasource"`
	From       time.Time                  `json:"from"`
	To         time.Time                  `json:"to"`
}

// ApiFilteredQueryDatasource defines model for ApiFilteredQueryDatasource.
type ApiFilteredQueryDatasource struct {
	Datasource ApiQueryDatasource              `json:"datasource"`
	Filters    []ApiQueryFilter                `json:"filters"`
	Type       *ApiFilteredQueryDatasourceType `json:"type,omitempty"`
}

// ApiFilteredQueryDatasourceType defines model for ApiFilteredQueryDatasource.Type.
type ApiFilteredQueryDatasourceType string

// ApiJoinQueryDatasource defines model for ApiJoinQueryDatasource.
type ApiJoinQueryDatasource struct {
	Datasources []ApiFilteredQueryDatasource   `json:"datasources"`
	JoinType    ApiJoinQueryDatasourceJoinType `json:"joinType"`
	Type        ApiJoinQueryDatasourceType     `json:"type"`
}

// ApiJoinQueryDatasourceJoinType defines model for ApiJoinQueryDatasource.JoinType.
type ApiJoinQueryDatasourceJoinType string

// ApiJoinQueryDatasourceType defines model for ApiJoinQueryDatasource.Type.
type ApiJoinQueryDatasourceType string

// ApiLogicalExpressionQueryField defines model for ApiLogicalExpressionQueryField.
type ApiLogicalExpressionQueryField struct {
	LogicalOperatorType ApiLogicalOperatorType             `json:"logicalOperatorType"`
	Operand1            ApiQueryField                      `json:"operand1"`
	Operand2            ApiQueryField                      `json:"operand2"`
	Type                ApiLogicalExpressionQueryFieldType `json:"type"`
	Urn                 string                             `json:"urn"`
}

// ApiLogicalExpressionQueryFieldType defines model for ApiLogicalExpressionQueryField.Type.
type ApiLogicalExpressionQueryFieldType string

// ApiLogicalOperatorType defines model for ApiLogicalOperatorType.
type ApiLogicalOperatorType = field.LogicalOperatorType

// ApiMetricDataType defines model for ApiMetricDataType.
type ApiMetricDataType = tsquery.DataType

// ApiNumericExpressionQueryField defines model for ApiNumericExpressionQueryField.
type ApiNumericExpressionQueryField struct {
	FieldUrn string                             `json:"fieldUrn"`
	Op       ApiBinaryNumericOperatorType       `json:"op"`
	Op1      ApiQueryField                      `json:"op1"`
	Op2      ApiQueryField                      `json:"op2"`
	Type     ApiNumericExpressionQueryFieldType `json:"type"`
}

// ApiNumericExpressionQueryFieldType defines model for ApiNumericExpressionQueryField.Type.
type ApiNumericExpressionQueryFieldType string

// ApiNvlQueryField defines model for ApiNvlQueryField.
type ApiNvlQueryField struct {
	AltField ApiQueryField        `json:"altField"`
	FieldUrn string               `json:"fieldUrn"`
	Source   ApiQueryField        `json:"source"`
	Type     ApiNvlQueryFieldType `json:"type"`
}

// ApiNvlQueryFieldType defines model for ApiNvlQueryField.Type.
type ApiNvlQueryFieldType string

// ApiOverrideFieldMetadataFilter defines model for ApiOverrideFieldMetadataFilter.
type ApiOverrideFieldMetadataFilter struct {
	FieldUrn          string                             `json:"fieldUrn"`
	Type              ApiOverrideFieldMetadataFilterType `json:"type"`
	UpdatedCustomMeta map[string]interface{}             `json:"updatedCustomMeta,omitempty"`
	UpdatedUnit       string                             `json:"updatedUnit,omitempty"`
	UpdatedUrn        string                             `json:"updatedUrn,omitempty"`
}

// ApiOverrideFieldMetadataFilterType defines model for ApiOverrideFieldMetadataFilter.Type.
type ApiOverrideFieldMetadataFilterType string

// ApiQueryDatasource defines model for ApiQueryDatasource.
type ApiQueryDatasource struct {
	union json.RawMessage
}

// ApiQueryField defines model for ApiQueryField.
type ApiQueryField struct {
	union json.RawMessage
}

// ApiQueryFieldMeta defines model for ApiQueryFieldMeta.
type ApiQueryFieldMeta struct {
	CustomMetadata map[string]interface{} `json:"customMetadata,omitempty"`
	DataType       ApiMetricDataType      `json:"dataType"`
	Required       bool                   `json:"required"`
	Unit           string                 `json:"unit,omitempty"`
	Uri            string                 `json:"uri"`
}

// ApiQueryFilter defines model for ApiQueryFilter.
type ApiQueryFilter struct {
	union json.RawMessage
}

// ApiQueryResult defines model for ApiQueryResult.
type ApiQueryResult struct {
	Data []ApiRawMetricValueRow `json:"data"`
	Meta ApiQueryResultMeta     `json:"meta"`
}

// ApiQueryResultMeta defines model for ApiQueryResultMeta.
type ApiQueryResultMeta struct {
	Fields []ApiQueryFieldMeta `json:"fields"`
}

// ApiRawMetricValueRow defines model for ApiRawMetricValueRow.
type ApiRawMetricValueRow = []any

// ApiRawQueryDatasource defines model for ApiRawQueryDatasource.
type ApiRawQueryDatasource struct {
	Config json.RawMessage           `json:"config"`
	Type   ApiRawQueryDatasourceType `json:"type"`
}

// ApiRawQueryDatasourceType defines model for ApiRawQueryDatasource.Type.
type ApiRawQueryDatasourceType string

// ApiReduceQueryField defines model for ApiReduceQueryField.
type ApiReduceQueryField struct {
	// FieldUrnsToReduce List of field urns to reduce, if empty, all fields will be reduced
	FieldUrnsToReduce []string                `json:"fieldUrnsToReduce,omitempty"`
	ReductionType     ApiReductionType        `json:"reductionType"`
	ResultCustomMeta  map[string]interface{}  `json:"resultCustomMeta,omitempty"`
	ResultUrn         string                  `json:"resultUrn"`
	Type              ApiReduceQueryFieldType `json:"type"`
}

// ApiReduceQueryFieldType defines model for ApiReduceQueryField.Type.
type ApiReduceQueryFieldType string

// ApiReductionType defines model for ApiReductionType.
type ApiReductionType = field.ReductionType

// ApiRefQueryField defines model for ApiRefQueryField.
type ApiRefQueryField struct {
	Type ApiRefQueryFieldType `json:"type"`
	Urn  string               `json:"urn"`
}

// ApiRefQueryFieldType defines model for ApiRefQueryField.Type.
type ApiRefQueryFieldType string

// ApiReplaceFieldFilter defines model for ApiReplaceFieldFilter.
type ApiReplaceFieldFilter struct {
	Field             ApiQueryField             `json:"field"`
	FieldUrnToReplace string                    `json:"fieldUrnToReplace"`
	Type              ApiReplaceFieldFilterType `json:"type"`
}

// ApiReplaceFieldFilterType defines model for ApiReplaceFieldFilter.Type.
type ApiReplaceFieldFilterType string

// ApiSelectorQueryField defines model for ApiSelectorQueryField.
type ApiSelectorQueryField struct {
	FalseField           ApiQueryField             `json:"falseField"`
	SelectorBooleanField ApiQueryField             `json:"selectorBooleanField"`
	TargetFieldUrn       string                    `json:"targetFieldUrn"`
	TrueField            ApiQueryField             `json:"trueField"`
	Type                 ApiSelectorQueryFieldType `json:"type"`
}

// ApiSelectorQueryFieldType defines model for ApiSelectorQueryField.Type.
type ApiSelectorQueryFieldType string

// ApiSingleFieldFilter defines model for ApiSingleFieldFilter.
type ApiSingleFieldFilter struct {
	Field ApiQueryField            `json:"field"`
	Type  ApiSingleFieldFilterType `json:"type"`
}

// ApiSingleFieldFilterType defines model for ApiSingleFieldFilter.Type.
type ApiSingleFieldFilterType string

// ApiStaticDataRow defines model for ApiStaticDataRow.
type ApiStaticDataRow struct {
	Timestamp time.Time `json:"timestamp"`
	Values    []any     `json:"values"`
}

// ApiStaticQueryDatasource defines model for ApiStaticQueryDatasource.
type ApiStaticQueryDatasource struct {
	Data       []ApiStaticDataRow           `json:"data"`
	FieldsMeta []ApiQueryFieldMeta          `json:"fieldsMeta"`
	Type       ApiStaticQueryDatasourceType `json:"type"`
}

// ApiStaticQueryDatasourceType defines model for ApiStaticQueryDatasource.Type.
type ApiStaticQueryDatasourceType string

// ApiUnaryNumericOperatorQueryField defines model for ApiUnaryNumericOperatorQueryField.
type ApiUnaryNumericOperatorQueryField struct {
	FieldUrn string                                `json:"fieldUrn"`
	Op       ApiUnaryNumericOperatorType           `json:"op"`
	Operand  ApiQueryField                         `json:"operand"`
	Type     ApiUnaryNumericOperatorQueryFieldType `json:"type"`
}

// ApiUnaryNumericOperatorQueryFieldType defines model for ApiUnaryNumericOperatorQueryField.Type.
type ApiUnaryNumericOperatorQueryFieldType string

// ApiUnaryNumericOperatorType defines model for ApiUnaryNumericOperatorType.
type ApiUnaryNumericOperatorType = field.UnaryNumericOperatorType

// ExecuteQueryJSONRequestBody defines body for ExecuteQuery for application/json ContentType.
type ExecuteQueryJSONRequestBody = ApiExecuteQueryCommandArgs

// AsApiCalendarAlignmentPeriod returns the union data inside the ApiAlignmentPeriod as a ApiCalendarAlignmentPeriod
func (t ApiAlignmentPeriod) AsApiCalendarAlignmentPeriod() (ApiCalendarAlignmentPeriod, error) {
	var body ApiCalendarAlignmentPeriod
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiCalendarAlignmentPeriod overwrites any union data inside the ApiAlignmentPeriod as the provided ApiCalendarAlignmentPeriod
func (t *ApiAlignmentPeriod) FromApiCalendarAlignmentPeriod(v ApiCalendarAlignmentPeriod) error {
	v.Type = "calendar"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// AsApiCustomAlignmentPeriod returns the union data inside the ApiAlignmentPeriod as a ApiCustomAlignmentPeriod
func (t ApiAlignmentPeriod) AsApiCustomAlignmentPeriod() (ApiCustomAlignmentPeriod, error) {
	var body ApiCustomAlignmentPeriod
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiCustomAlignmentPeriod overwrites any union data inside the ApiAlignmentPeriod as the provided ApiCustomAlignmentPeriod
func (t *ApiAlignmentPeriod) FromApiCustomAlignmentPeriod(v ApiCustomAlignmentPeriod) error {
	v.Type = "custom"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

func (t ApiAlignmentPeriod) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ApiAlignmentPeriod) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "calendar":
		return t.AsApiCalendarAlignmentPeriod()
	case "custom":
		return t.AsApiCustomAlignmentPeriod()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ApiAlignmentPeriod) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ApiAlignmentPeriod) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsApiRawQueryDatasource returns the union data inside the ApiQueryDatasource as a ApiRawQueryDatasource
func (t ApiQueryDatasource) AsApiRawQueryDatasource() (ApiRawQueryDatasource, error) {
	var body ApiRawQueryDatasource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiRawQueryDatasource overwrites any union data inside the ApiQueryDatasource as the provided ApiRawQueryDatasource
func (t *ApiQueryDatasource) FromApiRawQueryDatasource(v ApiRawQueryDatasource) error {
	v.Type = "raw"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// AsApiJoinQueryDatasource returns the union data inside the ApiQueryDatasource as a ApiJoinQueryDatasource
func (t ApiQueryDatasource) AsApiJoinQueryDatasource() (ApiJoinQueryDatasource, error) {
	var body ApiJoinQueryDatasource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiJoinQueryDatasource overwrites any union data inside the ApiQueryDatasource as the provided ApiJoinQueryDatasource
func (t *ApiQueryDatasource) FromApiJoinQueryDatasource(v ApiJoinQueryDatasource) error {
	v.Type = "join"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// AsApiStaticQueryDatasource returns the union data inside the ApiQueryDatasource as a ApiStaticQueryDatasource
func (t ApiQueryDatasource) AsApiStaticQueryDatasource() (ApiStaticQueryDatasource, error) {
	var body ApiStaticQueryDatasource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiStaticQueryDatasource overwrites any union data inside the ApiQueryDatasource as the provided ApiStaticQueryDatasource
func (t *ApiQueryDatasource) FromApiStaticQueryDatasource(v ApiStaticQueryDatasource) error {
	v.Type = "static"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

func (t ApiQueryDatasource) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ApiQueryDatasource) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "join":
		return t.AsApiJoinQueryDatasource()
	case "raw":
		return t.AsApiRawQueryDatasource()
	case "static":
		return t.AsApiStaticQueryDatasource()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ApiQueryDatasource) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ApiQueryDatasource) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsApiConstantQueryField returns the union data inside the ApiQueryField as a ApiConstantQueryField
func (t ApiQueryField) AsApiConstantQueryField() (ApiConstantQueryField, error) {
	var body ApiConstantQueryField
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiConstantQueryField overwrites any union data inside the ApiQueryField as the provided ApiConstantQueryField
func (t *ApiQueryField) FromApiConstantQueryField(v ApiConstantQueryField) error {
	v.Type = "constant"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// AsApiConditionQueryField returns the union data inside the ApiQueryField as a ApiConditionQueryField
func (t ApiQueryField) AsApiConditionQueryField() (ApiConditionQueryField, error) {
	var body ApiConditionQueryField
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiConditionQueryField overwrites any union data inside the ApiQueryField as the provided ApiConditionQueryField
func (t *ApiQueryField) FromApiConditionQueryField(v ApiConditionQueryField) error {
	v.Type = "condition"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// AsApiLogicalExpressionQueryField returns the union data inside the ApiQueryField as a ApiLogicalExpressionQueryField
func (t ApiQueryField) AsApiLogicalExpressionQueryField() (ApiLogicalExpressionQueryField, error) {
	var body ApiLogicalExpressionQueryField
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiLogicalExpressionQueryField overwrites any union data inside the ApiQueryField as the provided ApiLogicalExpressionQueryField
func (t *ApiQueryField) FromApiLogicalExpressionQueryField(v ApiLogicalExpressionQueryField) error {
	v.Type = "logicalExpression"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// AsApiRefQueryField returns the union data inside the ApiQueryField as a ApiRefQueryField
func (t ApiQueryField) AsApiRefQueryField() (ApiRefQueryField, error) {
	var body ApiRefQueryField
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiRefQueryField overwrites any union data inside the ApiQueryField as the provided ApiRefQueryField
func (t *ApiQueryField) FromApiRefQueryField(v ApiRefQueryField) error {
	v.Type = "ref"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// AsApiSelectorQueryField returns the union data inside the ApiQueryField as a ApiSelectorQueryField
func (t ApiQueryField) AsApiSelectorQueryField() (ApiSelectorQueryField, error) {
	var body ApiSelectorQueryField
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiSelectorQueryField overwrites any union data inside the ApiQueryField as the provided ApiSelectorQueryField
func (t *ApiQueryField) FromApiSelectorQueryField(v ApiSelectorQueryField) error {
	v.Type = "selector"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// AsApiNvlQueryField returns the union data inside the ApiQueryField as a ApiNvlQueryField
func (t ApiQueryField) AsApiNvlQueryField() (ApiNvlQueryField, error) {
	var body ApiNvlQueryField
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiNvlQueryField overwrites any union data inside the ApiQueryField as the provided ApiNvlQueryField
func (t *ApiQueryField) FromApiNvlQueryField(v ApiNvlQueryField) error {
	v.Type = "nvl"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// AsApiCastQueryField returns the union data inside the ApiQueryField as a ApiCastQueryField
func (t ApiQueryField) AsApiCastQueryField() (ApiCastQueryField, error) {
	var body ApiCastQueryField
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiCastQueryField overwrites any union data inside the ApiQueryField as the provided ApiCastQueryField
func (t *ApiQueryField) FromApiCastQueryField(v ApiCastQueryField) error {
	v.Type = "cast"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// AsApiNumericExpressionQueryField returns the union data inside the ApiQueryField as a ApiNumericExpressionQueryField
func (t ApiQueryField) AsApiNumericExpressionQueryField() (ApiNumericExpressionQueryField, error) {
	var body ApiNumericExpressionQueryField
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiNumericExpressionQueryField overwrites any union data inside the ApiQueryField as the provided ApiNumericExpressionQueryField
func (t *ApiQueryField) FromApiNumericExpressionQueryField(v ApiNumericExpressionQueryField) error {
	v.Type = "numericExpression"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// AsApiUnaryNumericOperatorQueryField returns the union data inside the ApiQueryField as a ApiUnaryNumericOperatorQueryField
func (t ApiQueryField) AsApiUnaryNumericOperatorQueryField() (ApiUnaryNumericOperatorQueryField, error) {
	var body ApiUnaryNumericOperatorQueryField
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiUnaryNumericOperatorQueryField overwrites any union data inside the ApiQueryField as the provided ApiUnaryNumericOperatorQueryField
func (t *ApiQueryField) FromApiUnaryNumericOperatorQueryField(v ApiUnaryNumericOperatorQueryField) error {
	v.Type = "unaryNumericOperator"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// AsApiReduceQueryField returns the union data inside the ApiQueryField as a ApiReduceQueryField
func (t ApiQueryField) AsApiReduceQueryField() (ApiReduceQueryField, error) {
	var body ApiReduceQueryField
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiReduceQueryField overwrites any union data inside the ApiQueryField as the provided ApiReduceQueryField
func (t *ApiQueryField) FromApiReduceQueryField(v ApiReduceQueryField) error {
	v.Type = "reduce"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

func (t ApiQueryField) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ApiQueryField) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "cast":
		return t.AsApiCastQueryField()
	case "condition":
		return t.AsApiConditionQueryField()
	case "constant":
		return t.AsApiConstantQueryField()
	case "logicalExpression":
		return t.AsApiLogicalExpressionQueryField()
	case "numericExpression":
		return t.AsApiNumericExpressionQueryField()
	case "nvl":
		return t.AsApiNvlQueryField()
	case "reduce":
		return t.AsApiReduceQueryField()
	case "ref":
		return t.AsApiRefQueryField()
	case "selector":
		return t.AsApiSelectorQueryField()
	case "unaryNumericOperator":
		return t.AsApiUnaryNumericOperatorQueryField()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ApiQueryField) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ApiQueryField) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsApiAlignerFilter returns the union data inside the ApiQueryFilter as a ApiAlignerFilter
func (t ApiQueryFilter) AsApiAlignerFilter() (ApiAlignerFilter, error) {
	var body ApiAlignerFilter
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiAlignerFilter overwrites any union data inside the ApiQueryFilter as the provided ApiAlignerFilter
func (t *ApiQueryFilter) FromApiAlignerFilter(v ApiAlignerFilter) error {
	v.Type = "aligner"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// AsApiAppendFieldFilter returns the union data inside the ApiQueryFilter as a ApiAppendFieldFilter
func (t ApiQueryFilter) AsApiAppendFieldFilter() (ApiAppendFieldFilter, error) {
	var body ApiAppendFieldFilter
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiAppendFieldFilter overwrites any union data inside the ApiQueryFilter as the provided ApiAppendFieldFilter
func (t *ApiQueryFilter) FromApiAppendFieldFilter(v ApiAppendFieldFilter) error {
	v.Type = "appendField"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// AsApiDropFieldFilter returns the union data inside the ApiQueryFilter as a ApiDropFieldFilter
func (t ApiQueryFilter) AsApiDropFieldFilter() (ApiDropFieldFilter, error) {
	var body ApiDropFieldFilter
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiDropFieldFilter overwrites any union data inside the ApiQueryFilter as the provided ApiDropFieldFilter
func (t *ApiQueryFilter) FromApiDropFieldFilter(v ApiDropFieldFilter) error {
	v.Type = "dropField"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// AsApiReplaceFieldFilter returns the union data inside the ApiQueryFilter as a ApiReplaceFieldFilter
func (t ApiQueryFilter) AsApiReplaceFieldFilter() (ApiReplaceFieldFilter, error) {
	var body ApiReplaceFieldFilter
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiReplaceFieldFilter overwrites any union data inside the ApiQueryFilter as the provided ApiReplaceFieldFilter
func (t *ApiQueryFilter) FromApiReplaceFieldFilter(v ApiReplaceFieldFilter) error {
	v.Type = "replaceField"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// AsApiConditionFilter returns the union data inside the ApiQueryFilter as a ApiConditionFilter
func (t ApiQueryFilter) AsApiConditionFilter() (ApiConditionFilter, error) {
	var body ApiConditionFilter
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiConditionFilter overwrites any union data inside the ApiQueryFilter as the provided ApiConditionFilter
func (t *ApiQueryFilter) FromApiConditionFilter(v ApiConditionFilter) error {
	v.Type = "condition"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// AsApiSingleFieldFilter returns the union data inside the ApiQueryFilter as a ApiSingleFieldFilter
func (t ApiQueryFilter) AsApiSingleFieldFilter() (ApiSingleFieldFilter, error) {
	var body ApiSingleFieldFilter
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiSingleFieldFilter overwrites any union data inside the ApiQueryFilter as the provided ApiSingleFieldFilter
func (t *ApiQueryFilter) FromApiSingleFieldFilter(v ApiSingleFieldFilter) error {
	v.Type = "singleField"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// AsApiOverrideFieldMetadataFilter returns the union data inside the ApiQueryFilter as a ApiOverrideFieldMetadataFilter
func (t ApiQueryFilter) AsApiOverrideFieldMetadataFilter() (ApiOverrideFieldMetadataFilter, error) {
	var body ApiOverrideFieldMetadataFilter
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApiOverrideFieldMetadataFilter overwrites any union data inside the ApiQueryFilter as the provided ApiOverrideFieldMetadataFilter
func (t *ApiQueryFilter) FromApiOverrideFieldMetadataFilter(v ApiOverrideFieldMetadataFilter) error {
	v.Type = "overrideFieldMetadata"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

func (t ApiQueryFilter) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ApiQueryFilter) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "aligner":
		return t.AsApiAlignerFilter()
	case "appendField":
		return t.AsApiAppendFieldFilter()
	case "condition":
		return t.AsApiConditionFilter()
	case "dropField":
		return t.AsApiDropFieldFilter()
	case "overrideFieldMetadata":
		return t.AsApiOverrideFieldMetadataFilter()
	case "replaceField":
		return t.AsApiReplaceFieldFilter()
	case "singleField":
		return t.AsApiSingleFieldFilter()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ApiQueryFilter) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ApiQueryFilter) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
